{% set version = "1.11.0" %}


package:
  name: hpx
  version: {{ version }}

source:
  url: https://github.com/STEllAR-GROUP/hpx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 01ec47228a2253b41e318bb09c83325a75021eb6ef3262400fbda30ac7389279

build:
  number: 4
  run_exports:
    weak:
      - {{ pin_subpackage("hpx", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - git                                        # [win]
    - ninja                                      # [not win]
  host:
    - asio
    - libboost-devel
    - gperftools                                 # [not win]
    - libhwloc
    - mimalloc                                   # [win]
    - python
  run:
    # Packages needed for downstream packages that use HPX at:
    # - build-time: headers, libraries
    # - runtime: shared libraries, interpreter (for hpxrun.py)
    # Only list packages whose meta.yaml doesn't contain a run_exports already
    - asio
    - libboost-headers
    - gperftools                                 # [not win]
    - python

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja                                      # [not win]
  files:
    - test/CMakeLists.txt
    - test/hello_hpx.cpp
  commands:
    # TODO: This seems to silently fail on Windows (but hpxrun.py is installed)
    - hpxrun.py --help

about:
  home: https://github.com/STEllAR-GROUP/hpx
  summary: The C++ Standard Library for Parallelism and Concurrency
  description: |
    HPX is a C++ Standard Library for Concurrency and Parallelism. It implements all of the
    corresponding facilities as defined by the C++ Standard. Additionally, in HPX we implement
    functionalities proposed as part of the ongoing C++ standardization process. We also extend
    the C++ Standard APIs to the distributed case.
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  doc_url: https://hpx.stellar-group.org/documentation
  dev_url: https://github.com/STEllAR-GROUP/hpx

extra:
  recipe-maintainers:
    - kordejong
    - oliverschmitz
    - hkaiser
